services:
  ohttps-webhook:
    image: mhmzx/ohttps-webhook:latest
    build:
      context: .
      args:
        APP_VERSION: test
    volumes:
      # - /etc/nginx/cert:/etc/nginx/cert
      - ./config.yaml:/app/config.yaml
      # - ./log:/app/log
    ports:
      - 8081:8081
    environment:
      SUP_GROUP_IDS: 994
